#!/bin/bash
# Source this file before launching Claude Code to enable KDA worker telemetry.
# It is intentionally inert unless KDA_OTEL_ENABLED=1.

if [ "${KDA_OTEL_ENABLED:-0}" != "1" ]; then
  return 0 2>/dev/null || exit 0
fi

KDA_OTEL_ENDPOINT="${KDA_OTEL_ENDPOINT:-http://127.0.0.1:4318}"
KDA_OTEL_ENDPOINT="${KDA_OTEL_ENDPOINT%/}"
KDA_OTEL_PROTOCOL="${KDA_OTEL_PROTOCOL:-http/json}"
KDA_OTEL_SERVICE_NAME="${KDA_OTEL_SERVICE_NAME:-kda-claude-worker}"

export CLAUDE_CODE_ENABLE_TELEMETRY=1
export CLAUDE_CODE_ENHANCED_TELEMETRY_BETA="${CLAUDE_CODE_ENHANCED_TELEMETRY_BETA:-1}"
export CLAUDE_CODE_OTEL_FLUSH_TIMEOUT_MS="${CLAUDE_CODE_OTEL_FLUSH_TIMEOUT_MS:-5000}"
export CLAUDE_CODE_OTEL_SHUTDOWN_TIMEOUT_MS="${CLAUDE_CODE_OTEL_SHUTDOWN_TIMEOUT_MS:-5000}"

export OTEL_SERVICE_NAME="$KDA_OTEL_SERVICE_NAME"
export OTEL_METRICS_EXPORTER=otlp
export OTEL_LOGS_EXPORTER=otlp
export OTEL_TRACES_EXPORTER=otlp
export OTEL_EXPORTER_OTLP_PROTOCOL="$KDA_OTEL_PROTOCOL"
export OTEL_EXPORTER_OTLP_ENDPOINT="$KDA_OTEL_ENDPOINT"
export OTEL_EXPORTER_OTLP_METRICS_PROTOCOL="$KDA_OTEL_PROTOCOL"
export OTEL_EXPORTER_OTLP_LOGS_PROTOCOL="$KDA_OTEL_PROTOCOL"
export OTEL_EXPORTER_OTLP_TRACES_PROTOCOL="$KDA_OTEL_PROTOCOL"
export OTEL_EXPORTER_OTLP_METRICS_ENDPOINT="${KDA_OTEL_METRICS_ENDPOINT:-$KDA_OTEL_ENDPOINT/v1/metrics}"
export OTEL_EXPORTER_OTLP_LOGS_ENDPOINT="${KDA_OTEL_LOGS_ENDPOINT:-$KDA_OTEL_ENDPOINT/v1/logs}"
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="${KDA_OTEL_TRACES_ENDPOINT:-$KDA_OTEL_ENDPOINT/v1/traces}"

# Keep raw prompt/body content out of telemetry. Tool metadata is useful for the
# plugin summary, but tool output content can be large and sensitive.
export OTEL_LOG_USER_PROMPTS="${OTEL_LOG_USER_PROMPTS:-false}"
export OTEL_LOG_TOOL_DETAILS="${OTEL_LOG_TOOL_DETAILS:-true}"
export OTEL_LOG_TOOL_CONTENT="${OTEL_LOG_TOOL_CONTENT:-false}"
export OTEL_LOG_RAW_API_BODIES="${OTEL_LOG_RAW_API_BODIES:-false}"

RESOURCE_ATTRIBUTES="service.name=$KDA_OTEL_SERVICE_NAME,kda.role=worker"
if [ -n "${KDA_TASK_ID:-}" ]; then
  RESOURCE_ATTRIBUTES="$RESOURCE_ATTRIBUTES,kda.task_id=$KDA_TASK_ID"
fi
if [ -n "${KDA_WORKSPACE:-}" ]; then
  RESOURCE_ATTRIBUTES="$RESOURCE_ATTRIBUTES,kda.workspace=$KDA_WORKSPACE"
fi
if [ -n "${OTEL_RESOURCE_ATTRIBUTES:-}" ]; then
  export OTEL_RESOURCE_ATTRIBUTES="$OTEL_RESOURCE_ATTRIBUTES,$RESOURCE_ATTRIBUTES"
else
  export OTEL_RESOURCE_ATTRIBUTES="$RESOURCE_ATTRIBUTES"
fi
